USE ICE;

SELECT * FROM CUSTOMER;
SELECT * FROM CUSTOMER_PRODUCTS;
SELECT * FROM PRODUCT;

SELECT DISTINCT CP.CUST_ID
FROM CUSTOMER_PRODUCTS CP, PRODUCT P  
WHERE  CP.PROD_ID IS NULL;

/* Creating a Common Table Expression (CTE) of 'NULL_CUST_IDS'  
	*/
WITH NULL_CUST_IDS AS
(
SELECT DISTINCT CP.CUST_ID
FROM CUSTOMER_PRODUCTS CP, PRODUCT P  
WHERE  CP.PROD_ID IS NULL
)
SELECT * FROM NULL_CUST_IDS;

/* Using Sub Querries to find Customers having no Product ID's  
	*/
SELECT C.CUST_NAME FROM CUSTOMER C WHERE 
(SELECT DISTINCT CP.CUST_ID FROM CUSTOMER_PRODUCTS CP, PRODUCT P  WHERE  CP.PROD_ID IS NULL) 
=  C.CUST_ID;




